#defaults:
#  - data: moab_5Kepi.yaml
#  - model: lightgbm.yaml
#  - simulator: moab_simparam.yaml

defaults:
  - data: quanser-rand.yaml
  - model: xgboost.yaml
  - simulator: quanser-log.yaml

# defaults:
#   - data: cartpole-updated.yaml
#   - model: SVR.yaml
#   - simulator: cartpole-updated-simparam.yaml
